version: "3"

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    restart: always
    networks:
      - nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ENABLE_IPV6=true
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - nginx-certs:/etc/nginx/certs
      - nginx-html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./logs/nginx:/var/log/nginx:z

networks:
  nginx-proxy:
    external:
      name: nginx-proxy


volumes:
  nginx-certs:
  nginx-html: