version: "3"

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ENABLE_IPV6=true
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - nginx-certs:/etc/nginx/certs
      - nginx-html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro

  nginx-lets-encrypt:
    image: nginxproxy/acme-companion:2.0
    restart: always
    depends_on:
      - nginx-proxy
    volumes:
      - acme:/etc/acme.sh
      - nginx-certs:/etc/nginx/certs
      - nginx-html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - vhost.d:/etc/nginx/vhost.d:z

networks:
  default:
    external:
      name: nginx-proxy


volumes:
  acme:
  nginx-certs:
  nginx-html:
  vhost.d: