version: "3"

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ENABLE_IPV6=true
      - DEFAULT_HOST="jebzpapy.tk"
    volumes:
      - nginx-certs:/etc/nginx/certs
      - nginx-html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - vhost:/etc/nginx/vhost.d

networks:
  default:
    external:
      name: nginx-proxy


volumes:
  nginx-certs:
  nginx-html:
  vhost: